<?php

namespace App\Services;

use App\Enums\AssetStatus;
use App\Models\Asset;
use App\Models\AssetTransfer;
use App\Models\StockItem;

class AssetService
{
    /** Append a row to the asset's ownership-change history. */
    private function logTransfer(Asset $asset, ?string $from, string $to, ?string $reason, ?string $performedBy): void
    {
        AssetTransfer::create([
            'asset_id' => $asset->id,
            'asset_tag' => $asset->tag,
            'asset_model' => $asset->model,
            'from_owner' => $from,
            'to_owner' => $to,
            'reason' => $reason,
            'performed_by' => $performedBy,
        ]);
    }

    /**
     * Create an asset from validated data. A blank tag is auto-generated by the
     * model; the first owner is also recorded as the initial owner.
     *
     * @param  array<string, mixed>  $data
     */
    public function create(array $data): Asset
    {
        if (blank($data['tag'] ?? null)) {
            unset($data['tag']);
        }
        if (blank($data['status'] ?? null)) {
            $data['status'] = AssetStatus::Ready->value;
        }
        if (blank($data['initial_owner'] ?? null) && ! blank($data['owner'] ?? null)) {
            $data['initial_owner'] = $data['owner'];
        }

        return Asset::create($data);
    }

    /**
     * Update an existing asset, keeping its tag if a blank one is submitted.
     *
     * @param  array<string, mixed>  $data
     */
    public function update(Asset $asset, array $data): Asset
    {
        if (blank($data['tag'] ?? null)) {
            unset($data['tag']);
        }
        $asset->update($data);

        return $asset->fresh();
    }

    /**
     * Hand an asset to a new owner. It enters "pending acceptance" until the
     * recipient confirms receipt.
     */
    public function transfer(Asset $asset, string $newOwner, ?string $reason = null, ?string $performedBy = null): Asset
    {
        $from = $asset->owner;
        $asset->update([
            'owner' => $newOwner,
            'status' => AssetStatus::PendingAcceptance,
            'last_reason' => $reason,
        ]);
        $this->logTransfer($asset, $from, $newOwner, $reason, $performedBy);

        return $asset->fresh();
    }

    /** Recipient confirms receipt: pending acceptance → deployed. */
    public function accept(Asset $asset): Asset
    {
        $asset->update(['status' => AssetStatus::Deployed]);

        return $asset->fresh();
    }

    /** Begin returning a deployed asset: deployed → pending return. */
    public function requestReturn(Asset $asset, ?string $reason = null): Asset
    {
        $asset->update([
            'status' => AssetStatus::PendingReturn,
            'last_reason' => $reason,
        ]);

        return $asset->fresh();
    }

    /** IT receives a returned asset back into the pool: pending return → ready. */
    public function markReceived(Asset $asset, ?string $performedBy = null): Asset
    {
        $from = $asset->owner;
        $asset->update([
            'status' => AssetStatus::Ready,
            'owner' => 'Pool — IT',
        ]);
        $this->logTransfer($asset, $from, 'Pool — IT', 'Returned to pool', $performedBy);

        return $asset->fresh();
    }

    /** Toggle maintenance: into Maintenance, or back to Deployed when leaving it. */
    public function toggleMaintenance(Asset $asset): Asset
    {
        $asset->update([
            'status' => $asset->status === AssetStatus::Maintenance ? AssetStatus::Deployed : AssetStatus::Maintenance,
        ]);

        return $asset->fresh();
    }

    /** Retire / write off an asset. */
    public function retire(Asset $asset, ?string $reason = null): Asset
    {
        $asset->update([
            'status' => AssetStatus::Writeoff,
            'last_reason' => $reason,
        ]);

        return $asset->fresh();
    }

    /**
     * Move an asset into the Stock module: create a stock item seeded from the
     * asset's details and mark the asset as pending-stock.
     *
     * @param  array{sku: string, qty: int, warehouse?: ?string, reason?: ?string}  $data
     */
    public function convertToStock(Asset $asset, array $data): StockItem
    {
        $item = StockItem::create([
            'sku' => $data['sku'],
            'name' => $asset->model,
            'serial' => $asset->serial,
            'brand' => $asset->brand,
            'model' => $asset->model,
            'unit' => 'unit',
            'cost' => $asset->value,
            'current_stock' => $data['qty'],
            'min_stock' => 0,
            'max_stock' => $data['qty'],
            'warehouse' => $data['warehouse'] ?? null,
            'supplier' => $asset->supplier,
            'last_move_at' => now(),
        ]);

        $asset->update([
            'status' => AssetStatus::PendingStock,
            'last_reason' => $data['reason'] ?? null,
        ]);

        return $item;
    }

    /**
     * Apply a single status to many assets at once (used by bulk Maintenance /
     * Write-off). Returns the number of assets updated.
     *
     * @param  list<int>  $ids
     */
    public function bulkSetStatus(array $ids, AssetStatus $status, ?string $reason = null): int
    {
        return Asset::whereIn('id', $ids)->update([
            'status' => $status->value,
            'last_reason' => $reason,
        ]);
    }
}
