import {
    Antenna,
    Battery,
    Bluetooth,
    Box,
    Boxes,
    Building2,
    Cable,
    Camera,
    Car,
    Cast,
    CircuitBoard,
    Cloud,
    Cog,
    Cpu,
    Database,
    Disc,
    Fan,
    Fingerprint,
    Gamepad2,
    HardDrive,
    HardDriveDownload,
    Headphones,
    Key,
    Keyboard,
    Laptop,
    Lightbulb,
    Lock,
    MemoryStick,
    Mic,
    Monitor,
    MonitorSmartphone,
    Mouse,
    Network,
    Package,
    PcCase,
    Phone,
    Plug,
    Power,
    Printer,
    Projector,
    Radio,
    Router,
    SatelliteDish,
    Scan,
    ScanLine,
    Server,
    Settings,
    ShieldCheck,
    Smartphone,
    Speaker,
    Tablet,
    Thermometer,
    Truck,
    Tv,
    Usb,
    Video,
    Watch,
    Webcam,
    Wifi,
    Wrench,
    Zap,
    type LucideIcon,
} from 'lucide-react';

/**
 * Curated set of Lucide icons offered in the icon picker (Settings → Master Data).
 * The chosen icon's **name** (e.g. "Laptop") is stored on the record; render it back
 * with getLucideIcon(name). Add entries here to widen the choice.
 */
export const ICON_OPTIONS: { name: string; Icon: LucideIcon }[] = [
    { name: 'Laptop', Icon: Laptop },
    { name: 'Monitor', Icon: Monitor },
    { name: 'MonitorSmartphone', Icon: MonitorSmartphone },
    { name: 'PcCase', Icon: PcCase },
    { name: 'Smartphone', Icon: Smartphone },
    { name: 'Tablet', Icon: Tablet },
    { name: 'Phone', Icon: Phone },
    { name: 'Printer', Icon: Printer },
    { name: 'Server', Icon: Server },
    { name: 'Database', Icon: Database },
    { name: 'HardDrive', Icon: HardDrive },
    { name: 'HardDriveDownload', Icon: HardDriveDownload },
    { name: 'Cpu', Icon: Cpu },
    { name: 'CircuitBoard', Icon: CircuitBoard },
    { name: 'MemoryStick', Icon: MemoryStick },
    { name: 'Keyboard', Icon: Keyboard },
    { name: 'Mouse', Icon: Mouse },
    { name: 'Router', Icon: Router },
    { name: 'Network', Icon: Network },
    { name: 'Wifi', Icon: Wifi },
    { name: 'Antenna', Icon: Antenna },
    { name: 'SatelliteDish', Icon: SatelliteDish },
    { name: 'Cable', Icon: Cable },
    { name: 'Usb', Icon: Usb },
    { name: 'Bluetooth', Icon: Bluetooth },
    { name: 'Cast', Icon: Cast },
    { name: 'Projector', Icon: Projector },
    { name: 'Camera', Icon: Camera },
    { name: 'Webcam', Icon: Webcam },
    { name: 'Video', Icon: Video },
    { name: 'Tv', Icon: Tv },
    { name: 'Headphones', Icon: Headphones },
    { name: 'Speaker', Icon: Speaker },
    { name: 'Mic', Icon: Mic },
    { name: 'Radio', Icon: Radio },
    { name: 'Battery', Icon: Battery },
    { name: 'Plug', Icon: Plug },
    { name: 'Power', Icon: Power },
    { name: 'Zap', Icon: Zap },
    { name: 'Scan', Icon: Scan },
    { name: 'ScanLine', Icon: ScanLine },
    { name: 'Fingerprint', Icon: Fingerprint },
    { name: 'Lock', Icon: Lock },
    { name: 'Key', Icon: Key },
    { name: 'ShieldCheck', Icon: ShieldCheck },
    { name: 'Cloud', Icon: Cloud },
    { name: 'Disc', Icon: Disc },
    { name: 'Gamepad2', Icon: Gamepad2 },
    { name: 'Watch', Icon: Watch },
    { name: 'Package', Icon: Package },
    { name: 'Box', Icon: Box },
    { name: 'Boxes', Icon: Boxes },
    { name: 'Wrench', Icon: Wrench },
    { name: 'Cog', Icon: Cog },
    { name: 'Settings', Icon: Settings },
    { name: 'Building2', Icon: Building2 },
    { name: 'Car', Icon: Car },
    { name: 'Truck', Icon: Truck },
    { name: 'Lightbulb', Icon: Lightbulb },
    { name: 'Fan', Icon: Fan },
    { name: 'Thermometer', Icon: Thermometer },
];

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(ICON_OPTIONS.map((o) => [o.name, o.Icon]));

/** Resolve a stored icon name to its Lucide component, or null when unknown/empty. */
export function getLucideIcon(name?: string | null): LucideIcon | null {
    return name ? (ICON_MAP[name] ?? null) : null;
}
