/**
 * The report module's chart palette — one ChartTone, three uses — shared by the tabular charts
 * (tabular-charts.tsx) and the summary tiles (summary-strip.tsx), so a status or a source wears
 * the same colour in a tile's meter as in the chart beside it.
 */
import type { ChartTone } from '../types';

/** Each tone as a fill (bars, swatches) and as a stroke (donut arcs). */
export const FILL: Record<ChartTone, string> = {
    green: 'bg-emerald-500',
    blue: 'bg-blue-500',
    violet: 'bg-violet-500',
    orange: 'bg-orange-500',
    amber: 'bg-amber-500',
    red: 'bg-red-500',
    pink: 'bg-pink-500',
    gray: 'bg-slate-400 dark:bg-slate-500',
    'soft-blue': 'bg-chart-soft-blue',
    'soft-green': 'bg-emerald-400',
    'soft-red': 'bg-red-400',
    'soft-amber': 'bg-amber-400',
    'soft-orange': 'bg-orange-400',
    'soft-violet': 'bg-violet-400',
    'soft-pink': 'bg-pink-400',
    'asset-deployed': 'bg-asset-deployed',
    'asset-ready': 'bg-asset-ready',
    'asset-pending-acceptance': 'bg-asset-pending-acceptance',
    'asset-common': 'bg-asset-common',
    'asset-pending-return': 'bg-asset-pending-return',
    'asset-writeoff': 'bg-asset-writeoff',
    'pair-orange': 'bg-chart-pair-orange',
    'pair-green': 'bg-chart-pair-green',
    'pair-rose': 'bg-chart-pair-rose',
    'pair-violet': 'bg-chart-pair-violet',
};
/** Each tone as text, for the counts printed over a stacked bar. */
export const TEXT: Record<ChartTone, string> = {
    green: 'text-emerald-600 dark:text-emerald-400',
    blue: 'text-blue-600 dark:text-blue-400',
    violet: 'text-violet-600 dark:text-violet-400',
    orange: 'text-orange-600 dark:text-orange-400',
    amber: 'text-amber-600 dark:text-amber-400',
    red: 'text-red-600 dark:text-red-400',
    pink: 'text-pink-600 dark:text-pink-400',
    gray: 'text-slate-500 dark:text-slate-400',
    'soft-blue': 'text-chart-soft-blue-ink',
    'soft-green': 'text-emerald-600 dark:text-emerald-400',
    'soft-red': 'text-red-600 dark:text-red-400',
    'soft-amber': 'text-amber-600 dark:text-amber-400',
    'soft-orange': 'text-orange-600 dark:text-orange-400',
    'soft-violet': 'text-violet-600 dark:text-violet-400',
    'soft-pink': 'text-pink-600 dark:text-pink-400',
    'asset-deployed': 'text-asset-deployed-ink',
    'asset-ready': 'text-asset-ready-ink',
    'asset-pending-acceptance': 'text-asset-pending-acceptance-ink',
    'asset-common': 'text-asset-common-ink',
    'asset-pending-return': 'text-asset-pending-return-ink',
    'asset-writeoff': 'text-asset-writeoff-ink',
    'pair-orange': 'text-chart-pair-orange-ink',
    'pair-green': 'text-chart-pair-green-ink',
    'pair-rose': 'text-chart-pair-rose-ink',
    'pair-violet': 'text-chart-pair-violet-ink',
};
export const STROKE: Record<ChartTone, string> = {
    green: 'stroke-emerald-500',
    blue: 'stroke-blue-500',
    violet: 'stroke-violet-500',
    orange: 'stroke-orange-500',
    amber: 'stroke-amber-500',
    red: 'stroke-red-500',
    pink: 'stroke-pink-500',
    gray: 'stroke-slate-400 dark:stroke-slate-500',
    'soft-blue': 'stroke-chart-soft-blue',
    'soft-green': 'stroke-emerald-400',
    'soft-red': 'stroke-red-400',
    'soft-amber': 'stroke-amber-400',
    'soft-orange': 'stroke-orange-400',
    'soft-violet': 'stroke-violet-400',
    'soft-pink': 'stroke-pink-400',
    'asset-deployed': 'stroke-asset-deployed',
    'asset-ready': 'stroke-asset-ready',
    'asset-pending-acceptance': 'stroke-asset-pending-acceptance',
    'asset-common': 'stroke-asset-common',
    'asset-pending-return': 'stroke-asset-pending-return',
    'asset-writeoff': 'stroke-asset-writeoff',
    'pair-orange': 'stroke-chart-pair-orange',
    'pair-green': 'stroke-chart-pair-green',
    'pair-rose': 'stroke-chart-pair-rose',
    'pair-violet': 'stroke-chart-pair-violet',
};
