<?php

namespace App\Services\Asset;

use App\Enums\Asset\AssetSource;
use App\Enums\Asset\AssetStatus;
use App\Models\Asset\Asset;
use App\Models\Asset\AssetTransfer;
use App\Models\Contract\Contract;
use App\Models\Employee\Employee;
use App\Models\User;
use App\Notifications\AssetAssignedNotification;
use App\Notifications\AssetReturnRequestedNotification;
use Illuminate\Support\Facades\Notification;

class AssetService
{
    /** Append a row to the asset's ownership-change history. */
    private function logTransfer(Asset $asset, ?string $from, string $to, ?string $reason, ?string $performedBy): void
    {
        AssetTransfer::create([
            'asset_id' => $asset->id,
            'asset_tag' => $asset->tag,
            'asset_model' => $asset->model?->name,
            'from_owner' => $from,
            'to_owner' => $to,
            'reason' => $reason,
            'performed_by' => $performedBy,
        ]);
    }

    /**
     * Create an asset from validated data. A blank tag is auto-generated by the
     * model; the first owner is also recorded as the initial owner.
     *
     * @param  array<string, mixed>  $data
     */
    public function create(array $data): Asset
    {
        if (blank($data['tag'] ?? null)) {
            unset($data['tag']);
        }
        if (blank($data['status'] ?? null)) {
            $data['status'] = AssetStatus::Ready->value;
        }
        if (blank($data['initial_owner'] ?? null) && ! blank($data['owner'] ?? null)) {
            $data['initial_owner'] = $data['owner'];
        }

        return Asset::create($this->normalizeAcquisition($data));
    }

    /**
     * Update an existing asset, keeping its tag if a blank one is submitted.
     *
     * @param  array<string, mixed>  $data
     */
    public function update(Asset $asset, array $data): Asset
    {
        if (blank($data['tag'] ?? null)) {
            unset($data['tag']);
        }
        $asset->update($this->normalizeAcquisition($data));

        return $asset->fresh();
    }

    /**
     * Normalise acquisition fields by source before saving:
     * - Rented: copy vendor, lease dates and value from the linked contract, and
     *   clear purchase/warranty fields (a lease has none of its own).
     * - Purchased: clear lease/contract fields; a lifetime warranty has no end date.
     *
     * @param  array<string, mixed>  $data
     * @return array<string, mixed>
     */
    private function normalizeAcquisition(array $data): array
    {
        if (($data['source'] ?? null) === AssetSource::Rented->value) {
            $contract = ! blank($data['contract_id'] ?? null) ? Contract::find($data['contract_id']) : null;
            if ($contract) {
                $data['supplier'] = $contract->vendor;
                $data['lease_start'] = $contract->start_date?->toDateString();
                $data['lease_end'] = $contract->end_date?->toDateString();
                $data['value'] = $contract->value;
            }
            $data['purchase_date'] = null;
            $data['warranty_end'] = null;
            $data['warranty_lifetime'] = false;

            return $data;
        }

        // Purchased: no lease or contract; a lifetime warranty carries no end date.
        $data['contract_id'] = null;
        $data['lease_start'] = null;
        $data['lease_end'] = null;
        if (! empty($data['warranty_lifetime'])) {
            $data['warranty_end'] = null;
        }

        return $data;
    }

    /**
     * Hand an asset to a new owner. It enters "pending acceptance" until the
     * recipient confirms receipt.
     */
    public function transfer(Asset $asset, string $newOwner, ?int $locationId = null, ?string $reason = null, ?string $performedBy = null): Asset
    {
        // A pooled asset has no owner — it "leaves" its warehouse, so stamp that
        // warehouse as the custody-trail origin instead of a blank sender.
        $from = $asset->owner ?: $asset->warehouse;
        $asset->update([
            'owner' => $newOwner,
            'location_id' => $locationId,
            'status' => AssetStatus::PendingAcceptance,
            'last_reason' => $reason,
        ]);
        $this->logTransfer($asset, $from, $newOwner, $reason, $performedBy);
        $this->notifyRecipient($asset, $newOwner, $from);

        return $asset->fresh();
    }

    /**
     * Bell alert to the recipient when an asset is handed over — only if the new
     * owner is an employee with a login account (pools / free-text owners get none).
     */
    private function notifyRecipient(Asset $asset, string $newOwner, ?string $from): void
    {
        $employee = Employee::where('code', $newOwner)->first();
        if (! $employee) {
            return;
        }

        // Only notify a recipient who can actually use My Assets (permission gates the bell).
        $user = User::where('employee_id', $employee->id)->first();
        if ($user && $user->hasPermission('assets.my')) {
            $user->notify(new AssetAssignedNotification($asset, $from));
        }
    }

    /** Recipient confirms receipt: pending acceptance → deployed, stamping the possession date. */
    public function accept(Asset $asset): Asset
    {
        $asset->update([
            'status' => AssetStatus::Deployed,
            'owned_since' => now(),
        ]);

        return $asset->fresh();
    }

    /** Begin returning a deployed asset: deployed → pending return; alert IT to receive it. */
    public function requestReturn(Asset $asset, ?string $reason = null): Asset
    {
        $holder = $asset->owner;
        $asset->update([
            'status' => AssetStatus::PendingReturn,
            'last_reason' => $reason,
        ]);

        // Bell alert to everyone who can receive assets back into the pool (permission gates the bell).
        $recipients = User::all()->filter(fn (User $u) => $u->hasPermission('assets.receive'));
        if ($recipients->isNotEmpty()) {
            Notification::send($recipients, new AssetReturnRequestedNotification($asset, $holder));
        }

        return $asset->fresh();
    }

    /**
     * IT receives a returned asset back into the pool: pending return → ready.
     * When a destination warehouse is supplied, the asset is stored there;
     * otherwise it keeps whatever warehouse it already had.
     */
    public function markReceived(Asset $asset, ?string $performedBy = null, ?string $warehouse = null): Asset
    {
        $from = $asset->owner;
        // Back in the pool = no owner (same as a freshly registered asset); its physical
        // whereabouts are the warehouse — which is also stamped as the custody-trail destination.
        $dest = filled($warehouse) ? $warehouse : $asset->warehouse;
        $asset->update([
            'status' => AssetStatus::Ready,
            'owner' => null,
            // No holder in the pool → no possession date.
            'owned_since' => null,
            'warehouse' => $dest,
        ]);
        $this->logTransfer($asset, $from, (string) $dest, 'Returned to pool', $performedBy);

        return $asset->fresh();
    }

    /** Retire / write off an asset. */
    public function retire(Asset $asset, ?string $reason = null): Asset
    {
        $asset->update([
            'status' => AssetStatus::Writeoff,
            'last_reason' => $reason,
        ]);

        return $asset->fresh();
    }

    /**
     * Apply a single status to many assets at once (used by bulk Write-off).
     * Returns the number of assets updated.
     *
     * @param  list<int>  $ids
     */
    public function bulkSetStatus(array $ids, AssetStatus $status, ?string $reason = null): int
    {
        return Asset::whereIn('id', $ids)->update([
            'status' => $status->value,
            'last_reason' => $reason,
        ]);
    }
}
